// Code generated by "stringer -type syzcall,mountflag"; DO NOT EDIT.

package namespace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BIND-2]
	_ = x[CHDIR-3]
	_ = x[UNMOUNT-35]
	_ = x[MOUNT-46]
	_ = x[RFORK-19]
	_ = x[IMPORT-7]
	_ = x[INCLUDE-14]
}

const (
	_syzcall_name_0 = "BINDCHDIR"
	_syzcall_name_1 = "IMPORT"
	_syzcall_name_2 = "INCLUDE"
	_syzcall_name_3 = "RFORK"
	_syzcall_name_4 = "UNMOUNT"
	_syzcall_name_5 = "MOUNT"
)

var (
	_syzcall_index_0 = [...]uint8{0, 4, 9}
)

func (i syzcall) String() string {
	switch {
	case 2 <= i && i <= 3:
		i -= 2
		return _syzcall_name_0[_syzcall_index_0[i]:_syzcall_index_0[i+1]]
	case i == 7:
		return _syzcall_name_1
	case i == 14:
		return _syzcall_name_2
	case i == 19:
		return _syzcall_name_3
	case i == 35:
		return _syzcall_name_4
	case i == 46:
		return _syzcall_name_5
	default:
		return "syzcall(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REPL-0]
	_ = x[BEFORE-1]
	_ = x[AFTER-2]
	_ = x[CREATE-4]
	_ = x[CACHE-16]
}

const (
	_mountflag_name_0 = "REPLBEFOREAFTER"
	_mountflag_name_1 = "CREATE"
	_mountflag_name_2 = "CACHE"
)

var (
	_mountflag_index_0 = [...]uint8{0, 4, 10, 15}
)

func (i mountflag) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _mountflag_name_0[_mountflag_index_0[i]:_mountflag_index_0[i+1]]
	case i == 4:
		return _mountflag_name_1
	case i == 16:
		return _mountflag_name_2
	default:
		return "mountflag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
